### ISSUE TITLE
Add --project and -p command line option

### ISSUE THREAD

**Issue by codeBelt** [allegro/typescript-strict-plugin#11]
Currently we use `"strict": true` but have `"strictNullChecks": false`. When we run `yarn tsc-strict` we get `🎉  All files passed`. 

```json
{
 "compilerOptions": {
   ...
   "strict": true,
   "strictNullChecks": false,
   "plugins": [
    {
     "name": "typescript-strict-plugin"
    }
   ]
 }
}
```

I am not sure how the plugin should work but I thought it would ignore the `strictNullChecks` and make it `true`.

I would like to keep the `tsconfig.json` as is and not remove `"strictNullChecks": false` so it can work with our current workflow. Can you allow `tsc-strict` to take the `--project` and `-p` [command line options](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#using-tsconfigjson-or-jsconfigjson) so we can point to another file (`tsc-strict -p tsconfig-strict.json`)?

**Comment by codeBelt** [comment]
I ended up renaming `tsconfig.json` to `tsconfig-base.json` and made `tsconfig.json` look like:

```json
{
  "extends": "./tsconfig-base.json",
  "compilerOptions": {
    "strict": true,
    "strictNullChecks": true,
    "plugins": [
      {
        "name": "typescript-strict-plugin",
        "paths": ["./src/stores/", "./src/utils/"]
      }
    ]
  }
}
```

I think this works better because now my IDE displays the stricter warnings/errors but our build process can use the less strict version. 

Maybe there should be a way to tell `tsc-strict` to override `strictNullChecks` or one of the other option(s) that is combined under the `strict` option? Then I wouldn't have to do the tsconfig extend thing.

**Comment by codeBelt** [comment]
I guess my team is not liking all the strict null warnings in the IDE. Maybe allowing `tsc-strict` to accept the `--project` and `-p` [command line options](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#using-tsconfigjson-or-jsconfigjson) is not a bad idea. Then I can slowly clean up the null warnings without the team seeing them.

**Comment by KostkaBrukowa** [comment]
To be honest we could actually pass all the arguments that typescript supports to the `tsc` not only `--project`. Right now we only pass `--strict --noEmit` but adding support to pass `--project` and the rest would be nice feature. I'll try to add this over the weekend. Thanks for the idea
