### ISSUE TITLE
files as an option of tsc-strict

### ISSUE THREAD

**Issue by xiluo58** [allegro/typescript-strict-plugin#15]
Is it possible to add an option to pass a list of files?

My use case is only check changed files. The easiest way to achieve this is passing the files as an argument to tsc-strict

**Comment by kamkry** [comment]
Hi, the tool is built to allow adding strict mode incrementally, so you should add `@ts-strict` comment only to files, where you want to have strict errors in and you're able to fix them.

Besides, our CLI uses tsc under the hood, and I don't think there's a way to list files there outside of tsconfig.json. But if you have an idea how to do it, feel free to propose it or do it yourself 😄  (but just a heads up, we plan to release a big update to our internals soon, so I'd do it afterwards)
