### ISSUE TITLE
When ts-strict-ignore will be released?

### ISSUE THREAD

**Issue by aleksandrlat** [allegro/typescript-strict-plugin#18]
Sorry this is just a question
I found `ts-strict-ignore` branch and it looks interesting
When will it be released?
Thank you!

**Comment by aleksandrlat** [comment]
Do you need the help to move it through finish line?

**Comment by kamkry** [comment]
Hi, the 2.0 is in review process #19, we'll publish it after some manual testing to check if everything is alright

**Comment by aleksandrlat** [comment]
Great! Thank you @kamkry!
