### ISSUE TITLE
`update-strict-comments` not working.

### ISSUE THREAD

**Issue by marcomoonpay** [allegro/typescript-strict-plugin#24]
I'm running V2. I've followed the README guide for installation. I've run the command `update-strict-comments`. Here's the output:

```
🎯 Found 2131 strict files
🔧 Updated comments in 0 files
```

However my files are not strict at all!

Here's my `tsconfig.json`
```json
  "compilerOptions": {
    "inlineSourceMap": true,
    "inlineSources": true,
    "noImplicitAny": false,
    "noUnusedLocals": true,
    "pretty": true,
    "lib": ["ES2020", "dom"],
    "module": "CommonJS",
    "moduleResolution": "node",
    "target": "ES2018",
    "declaration": true,
    "skipLibCheck": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "incremental": true,
    "esModuleInterop": true,
    "strict": false,
    "plugins": [
      {
        "name": "typescript-strict-plugin",
        "paths": ["./src"]
      }
    ]
  }
```

**Comment by marcomoonpay** [comment]
Hi! I have an update on this issue. If I remove
`"pretty": true`

Frome the above `tsconfig.json` file, it works!

**Comment by KostkaBrukowa** [comment]
Hmmm... that's weird. Honestly I think it's a bug in our plugin and I wouldn't put that flag inside the readme but I would just fix the issue itself. I'm marking it as a bug and we'll try to fix this.
Thanks for reporting this!

**Comment by marcomoonpay** [comment]
No problem! For now we will start the integration in our codebase with `pretty: false` 👍
