### ISSUE TITLE
The same project doesn't work

### ISSUE THREAD

**Issue by tavi100** [allegro/typescript-strict-plugin#49]
I opened the sample project in Visual Studio Code and it doesn't work: neither main.ts nor otherFile.ts are highlighted.
VSC is the latest version - 1.73.0, there is no code change from the original.

Let me know if you need any other info

<img width="326" alt="image" src="https://user-images.githubusercontent.com/108861996/200567358-d7608757-6642-4727-bf78-a8b578eb881d.png">
<img width="373" alt="image" src="https://user-images.githubusercontent.com/108861996/200567390-5b89df98-da40-4831-a755-6cf7361e37ca.png">

**Comment by tavi100** [comment]
My bad, I was doing something wrong.

**Comment by ipanasenko** [comment]
Hey @tavi100!
Can you sure what you did wrong, if you remember?
I can't make this plugin work anywhere, including sample project
