### ISSUE TITLE
Doesn't work with TS 5.2. No errors shown at all.

### ISSUE THREAD

**Issue by zorzysty** [allegro/typescript-strict-plugin#57]
The plugin works fine with TS 5.1.6, but upgrading to 5.2.2 with the plugin enabled, completely turns off any TS errors in the IDE (not only strict mode errors - all others as well). This happens both in VSCode and Webstorm. 

Dropping to 5.1.6 makes the plugin work again, and removing the plugin makes 5.2.2 show "normal" (non-strict) errors in the IDE.

**Comment by zorzysty** [comment]
I've managed to dig this up from IDE's logs:
```
#c.i.l.j.s.JSLanguageServiceQueue - Service internal error: Error processing request. Cannot read properties of undefined (reading 'getSyntacticDiagnostics')
TypeError: Cannot read properties of undefined (reading 'getSyntacticDiagnostics')
```
Could be useful for debugging this.

@KostkaBrukowa If you have some rough idea of what might be causing this and could point me in a right direction, I'd be happy to contribute.

**Comment by KostkaBrukowa** [comment]
Hey! Sorry for delay. @kamkry actually found the culprit: [here](https://github.com/allegro/typescript-strict-plugin/blob/master/src/plugin/utils.ts#L8) and [here](https://github.com/allegro/typescript-strict-plugin/blob/master/src/plugin/utils.ts#L15) should be 

```
info.project['compilerOptions'].strict = true;
```
so the API changed in TS 5.2.2

**Comment by kamkry** [comment]
Hi @zorzysty! We released the fix in the latest beta, could you check if it's working correctly now? 
```bash
npm i typescript-strict-plugin@2.2.1-beta.1
```

**Comment by zorzysty** [comment]
@kamkry It's definitely better, but something is still a bit off. Now I see strict mode errors when I open and edit a file, but they disappear when I restart TS Language server or change anything in tsconfig.json. To get them back, I need to reopen the file. This is not happening with 5.1.6 and the previous version of the plugin.

**Comment by kamkry** [comment]
@zorzysty We tried to quickly find the problem but we need more time. It's good to hear the fix helped you, I opened the pull request and we'll try to release it as soon as it's possible, thank you for creating the issue 😄
