### ISSUE TITLE
idea: script that looks for files that can have @ts-strict added to them

### ISSUE THREAD

**Issue by sudall** [allegro/typescript-strict-plugin#6]
- script takes in a folder (or list of files) and recursively looks at each TS file
- if the TS file doesn't have errors with strict mode turned on and doesn't have the //@ts-strict directive, the script would add //@ts-strict to the top of the file.

This might help for scenarios where //@ts-strict is available, but not everyone on the dev team knows about it or maybe has forgotten to use it, and also just to avoid the manual effort of trying to figure out which files are already strict compatible.

Along this same train of thought... another idea could be a pre-commit hook that checks to make sure new TS files have //@ts-strict and checks to see if existing ones can have //@ts-strict added to them.

**Comment by kamkry** [comment]
Hi, we're working on an update which has a tool to do exactly that. Thanks for your idea, and stay tuned!
