### ISSUE TITLE
Plugin is not working on a Directories

### ISSUE THREAD

**Issue by shsuman** [allegro/typescript-strict-plugin#7]
Working fine with //@ts-strict but doesn't work when I set 
`
{
    ...
    "plugins": [
            {
                "name": "typescript-strict-plugin",
                "paths": [
                    "./src/v2"
                ]
            }
        ]
}
`

**Comment by KostkaBrukowa** [comment]
Can you provide some more information? What is your folder structure? Maybe a sample repo to clone for us to check what's wrong?

**Comment by shsuman** [comment]
Here's a repo that I created: https://github.com/shsuman/ts-plugin-test 

It has a file ./src/v2/1.ts. And the tsconfig looks like this.
{
    "compilerOptions": {
        "allowJs": true,
        "alwaysStrict": true,
        "declaration": false,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "forceConsistentCasingInFileNames": true,
        "module": "commonjs",
        "moduleResolution": "node",
        "noUnusedLocals": true,
        "outDir": "./dist",
        "baseUrl": "./src",
        "plugins": [
            {
                "name": "typescript-strict-plugin",
                "paths": [
                    "./src/v2"
                ]
            }
        ],
        "resolveJsonModule": true,
        "skipLibCheck": true,
        "sourceMap": true,
        "strict": false,
        "target": "es6"
    }
}

When I open it in VSCode, no errors are shown in the editor, however when I add the comment "//@ts-strict", it works fine.

**Comment by KostkaBrukowa** [comment]
Hmmm... i've cloned the repository and I have an error there. Are you sure that you have correct typescript version selected as shown in last screenshot below?

![Zrzut ekranu 2021-08-20 o 12 05 41](https://user-images.githubusercontent.com/35625949/130217594-25b8a654-f494-4bd9-b7a1-49cd9615dc90.jpg)
![Zrzut ekranu 2021-08-20 o 12 05 46](https://user-images.githubusercontent.com/35625949/130217600-b83210c0-8fa4-4d0f-b173-6323e7f02bc1.jpg)
![image](https://user-images.githubusercontent.com/35625949/130217792-9e6596e6-d677-426b-8b6f-d40f1805caea.png)

**Comment by shsuman** [comment]
@KostkaBrukowa, Are you testing on a windows machine or Linux machine ? I am on a windows machine.

**Comment by KostkaBrukowa** [comment]
I'm testing on MacOS. Good idea I'll check on Windows machine and see if it works there

**Comment by shsuman** [comment]
And yes, I do have the correct typescript version selected :)

**Comment by KostkaBrukowa** [comment]
Ok. Thanks for submitting the issue. There is an error on windows machines due to having `\` instead of `/` in paths and different endlines. PR is on the way. Thanks again
